const shell=document.querySelector('#app-shell'),view=document.querySelector('#onboarding-view');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qs=[['Como sua empresa se chama?','name','Ex.: Clínica Aurora'],['O que sua empresa oferece?','offer','Produtos, serviços e diferencial'],['Quem você quer atrair?','audience','Descreva seu público ideal'],['Qual é o principal objetivo agora?','goal','Ex.: gerar mais leads'],['Quais canais já utiliza?','channels','Ex.: Instagram, Google, site']];let i=0,data=JSON.parse(localStorage.getItem('orquestra-profile')||'{}');
document.querySelectorAll('a[href^="#"]').forEach(a=>a.onclick=e=>{let t=document.querySelector(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth'})}});
function openApp(){shell.classList.add('is-open');render()};function closeApp(){shell.classList.remove('is-open')};function render(){let q=qs[i];view.innerHTML=`<div class="app-progress">ONBOARDING <span>${i+1} / ${qs.length}</span></div><h2>${q[0]}</h2><p class="app-intro">A Juliana vai usar esta informação para construir a inteligência da sua marca.</p><form><input id="answer" placeholder="${q[2]}" value="${esc(data[q[1]]||'')}" required><div class="app-actions"><button type="button" class="text-button" id="back" ${i?'':'disabled'}>← Voltar</button><button class="primary-button">${i===qs.length-1?'Criar meu perfil':'Continuar'} <b>↗</b></button></div></form>`;view.querySelector('form').onsubmit=e=>{e.preventDefault();data[q[1]]=view.querySelector('#answer').value.trim();if(i<qs.length-1){i++;render()}else{localStorage.setItem('orquestra-profile',JSON.stringify(data));profile()}};view.querySelector('#back').onclick=()=>{if(i){i--;render()}};view.querySelector('#answer').focus()}
function profile(){view.innerHTML=`<div class="app-progress">PERFIL ESTRATÉGICO <span>PRONTO</span></div><p class="eyebrow"><i></i> Juliana IA ativada</p><h2>${esc(data.name)}<br><mark>tem uma direção.</mark></h2><div class="profile-grid"><div><span>NEGÓCIO</span><p>${esc(data.offer)}</p></div><div><span>PÚBLICO</span><p>${esc(data.audience)}</p></div><div><span>OBJETIVO</span><p>${esc(data.goal)}</p></div><div><span>CANAIS</span><p>${esc(data.channels)}</p></div></div><div class="julia-message"><strong>JULIANA IA <em>online</em></strong><p>Entendi o contexto inicial de ${esc(data.name)}. Vou priorizar “${esc(data.goal)}” e organizar os agentes para começar o planejamento.</p><button class="primary-button" onclick="julia()">Conversar com a Juliana <b>↗</b></button></div>`}
function julia(){view.innerHTML=`<div class="app-progress">JULIANA IA <span>ESTRATEGISTA</span></div><h2>Por onde começamos?</h2><p class="app-intro">Seu perfil está conectado. Peça um plano, uma campanha ou uma análise.</p><div class="suggestions"><button data-action="plan">Crie meu plano de 30 dias</button><button data-action="priorities">Defina minhas prioridades</button><button data-action="campaign">Monte uma campanha</button></div><div class="julia-message"><strong>CONTEXTO ATIVO</strong><p>Trabalhando para <b>${esc(data.name)}</b>, com foco em <b>${esc(data.goal)}</b>. Os agentes estão prontos para receber tarefas.</p></div>`;view.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action))}
function action(type){const content={plan:['PLANO DE 30 DIAS',`Para ${esc(data.name)}, vou organizar o primeiro ciclo em quatro movimentos: diagnóstico e mensagem na semana 1; produção de conteúdo na semana 2; campanha e distribuição na semana 3; análise e otimização na semana 4. O próximo passo é transformar isso em tarefas para os agentes.`],priorities:['PRIORIDADES ESTRATÉGICAS',`Com base no objetivo “${esc(data.goal)}”, as três prioridades são: definir uma oferta clara; criar uma sequência de conteúdo para ${esc(data.audience)}; e estabelecer uma rotina de medição nos canais ${esc(data.channels)}.`],campaign:['CAMPANHA INICIAL',`Sugestão de campanha para ${esc(data.name)}: uma mensagem central focada em “${esc(data.goal)}”, com conteúdo de atração, prova social e uma chamada para ação. Vou encaminhar o briefing ao Redator, Designer, Social Media e Analista.`]}[type];view.innerHTML=`<div class="app-progress">JULIANA IA <span>RESPOSTA GERADA</span></div><p class="eyebrow"><i></i> ${content[0]}</p><h2>Primeiro movimento<br><mark>definido.</mark></h2><div class="julia-message"><strong>JULIANA IA <em>online</em></strong><p>${content[1]}</p></div><div class="app-actions"><button class="text-button" onclick="julia()">← Voltar</button><button class="primary-button" onclick="julia()">Escolher próxima ação <b>↗</b></button></div>`}
document.querySelector('#start-onboarding').onclick=openApp;document.querySelector('#close-app').onclick=closeApp;shell.onclick=e=>{if(e.target===shell)closeApp()};
